
servers:
  # A dyn-recfg server definition
  bob:
    # The dyn-recfg type (it is actually a python module) - don't forget the 'Config' suffix!
    module: feed_the_troll.cfg.DemoConfig
    # namespace is optional...if not set, it will create the dyn-recfg server in the reconfiguration node's private namespace (/reconfiguration/bob)
    # overrides are optional...if not set, they will default to those in the .cfg files

  # Another dyn-recfg server definition
  dudette:
    module: feed_the_troll.cfg.DemoConfig
    # direct the dyn-recfg server to be created elsewhere (/foo/troll/dudette)
    namespace: /foo/troll
    # overrides are optional...and can be partial, again defaults to those in the .cfg files
    overrides:
      # int_param: 5
      double_param: 0.6
      str_param: Dudette
      bool_param: False
      size: 2
