
servers:
  # A dyn-recfg server definition - with this name it will be found at 'reconfiguration/dude'
  dude:
    # The dyn-recfg type (it is actually a python module) - don't forget the 'Config' suffix!
    module: feed_the_troll.cfg.DemoConfig
    # Load some initialisations to the param server that override those in the .cfg files
    overrides:
      int_param: 5
      double_param: 0.6
      str_param: Dude
      bool_param: False
      size: 2

  # Another dyn-recfg server definition - will be found at 'reconfiguration/dudette'
  dudette:
    module: feed_the_troll.cfg.DemoConfig
    # optionally direct the reconfigure server to be somewhere other than the reconfiguration server's private namespace
    namespace: /foo/troll
    overrides:
      int_param: 5
      double_param: 0.6
      str_param: Dudette
      bool_param: False
      size: 2
